version: '3'
services:
  galois_theory:
    build:
      context: .
      args:
        USERNAME: ${USERNAME}
        UID: ${UID}
        GID: ${GID}
    user: "${UID}:${GID}"
    stdin_open: true
    tty: true
    working_dir: "/galois_theory"
    volumes:
      - "../:/galois_theory"
